# Generated by Django 3.2.5 on 2021-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.CharField(default=models.CharField(blank=True, max_length=300), max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
